export const LOGO = require('../assets/Homepage/Logo.png');
export const INSTAGRAM_ICON = require('../assets/Footer/instagram.png')
export const LINKEDIN_ICON = require('../assets/Footer/linkedin.png')
export const WHATSAPP_ICON = require('../assets/Footer/whatsapp.png')
export const MAIL_ICON = require('../assets/icons/mail.png')
export const LOKSABHAIMAGE = require('../assets/Commitee/loksabha.jpg');
export const PARALLELUNIVERSEIMAGE = require('../assets/Commitee/Parallel Universe Art.jpeg');
export const GALEGAL1IMAGE = require('../assets/Commitee/galegal1.jpg');
export const UNSCIMAGE = require('../assets/Commitee/unsc.jpg');
export const UNHRCIMAGE = require('../assets/Commitee/unhrc.jpg');
export const NCWIMAGE = require('../assets/Commitee/ncw.jpg');
export const MAHABHARATIMAGE = require('../assets/Commitee/mahabharat.jpg');
export const GALEGAL2IMAGE = require('../assets/Commitee/galegal2.jpg');
export const MRN_LOGO = require('../assets/Intro_Theme/Mrn logo.png')
export const COMMITEE1 = require('../assets/Commitee/picture 1.jpg')
export const COMMITEE2 = require('../assets/Commitee/picture 2.jpg')
export const COMMITEE3 = require('../assets/Commitee/picture 3.jpg')
export const FOUNDERBG = require('../assets/Homepage/founderbg.jpg');
export const FOUNDER_IMAGE = require('../assets/Homepage/Founder Secretary.jpg')