export const LOGO = require('../assets/Homepage/Logo.png');
export const FACEBOOK = require('../assets/Contact Us/ic--baseline-facebook.png')
export const TWITEER = require('../assets/Contact Us/twiteer.png')
export const YOUTUBE = require('../assets/Contact Us/entypo-social_youtube-with-circle.png')
export const LINKEDIN = require('../assets/Contact Us/entypo-social_linkedin-with-circle.png')
export const LINKEDIN_ICON = require('../assets/Footer/linkedin.png')
export const INSTAGRAM_ICON = require('../assets/Footer/instagram.png')
export const WHATSAPP_ICON = require('../assets/Footer/whatsapp.png')
export const MAIL_ICON = require('../assets/icons/mail.png')
export const MAIL = require('../assets/Contact Us/mail.jpg')
export const LOKSABHAIMAGE = require('../assets/Commitee/loksabha.jpg');
export const PARALLELUNIVERSEIMAGE = require('../assets/Commitee/Parallel Universe Art.jpeg');
export const GALEGAL1IMAGE = require('../assets/Commitee/galegal1.jpg');
export const UNSCIMAGE = require('../assets/Commitee/unsc.jpg');
export const UNHRCIMAGE = require('../assets/Commitee/unhrc.jpg');
export const NCWIMAGE = require('../assets/Commitee/ncw.jpg');
export const MAHABHARATIMAGE = require('../assets/Commitee/mahabharat.jpg');
export const GALEGAL2IMAGE = require('../assets/Commitee/galegal2.jpg');
export const MRN_LOGO = require('../assets/Intro_Theme/Mrn logo.png')
export const COMMITEE1 = require('../assets/Commitee/picture 1.jpg')
export const COMMITEE2 = require('../assets/Commitee/picture 2.jpg')
export const COMMITEE3 = require('../assets/Commitee/picture 3.jpg')
export const FOUNDERBG = require('../assets/Homepage/founderbg.jpg');
export const FOUNDER_IMAGE = require('../assets/Homepage/Founder Secretary.jpg')
export const PHONE_ICON = require('../assets/Contact Us/phone.png')
export const VISION_IMAGE = require('../assets/Intro_Theme/image.png')
export const IMAGE_2 = require('../assets/Intro_Theme/img2.png')
export const PROFILE_IMAGE_1 = require('../assets/profile/WhatsApp Image 2024-09-02 at 18.46.04_cd4d8584.jpg')
export const PROFILE_IMAGE_2 = require('../assets/profile/arpit.jpg')
export const QR_CODE = require('../assets/QR-TIS.jpg')